# Generated by Django 5.2.4 on 2025-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('cargo_atual', models.CharField(max_length=100)),
                ('resumo_profissional', models.TextField()),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField(blank=True, null=True)),
                ('atual', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('Graduação', 'Graduação'), ('Pós-Graduação', 'Pós-Graduação'), ('Técnico', 'Técnico'), ('Curso Livre', 'Curso Livre')], max_length=20)),
                ('ano_conclusao', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Completo', 'Completo'), ('Em andamento', 'Em andamento'), ('Trancado', 'Trancado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado')], max_length=20)),
                ('categoria', models.CharField(choices=[('Back-end', 'Back-end'), ('Front-end', 'Front-end'), ('Fullstack', 'Fullstack'), ('DevOps', 'DevOps'), ('Banco de Dados', 'Banco de Dados'), ('Cloud', 'Cloud'), ('Outros', 'Outros')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado'), ('Fluente', 'Fluente'), ('Nativo', 'Nativo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('link_repositorio', models.URLField(blank=True)),
                ('link_demo', models.URLField(blank=True)),
                ('tecnologias', models.CharField(max_length=255)),
                ('data_publicacao', models.DateField()),
            ],
        ),
    ]
